import { auth } from "@/auth"
import { redirect } from "next/navigation";
import { Metadata } from "next"
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
    title: "Astralics | Settings",
    description: "Generated by create next app",
};
  

export default async function Page() {
    const session = await auth();
    if(!session?.user) redirect('/login');
    return (
        <>
        <h1 className="font-bold text-3xl">Settings</h1>
        <Separator />
        </>
    )
}