import { auth } from "@/auth"
import { redirect } from "next/navigation";
import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Astralics | Settings",
    description: "Generated by create next app",
};
  

export default async function Page() {
    const session = await auth();
    if(!session?.user) redirect('/login');
    return (
        <>
        
        </>
    )
}