import { Metadata } from "next"
import { auth } from "@/auth"
import { Navbar } from "@/components/Navbar"

export const metadata: Metadata = {
  title: "Astralics | Feedback at your fingertips.",
  description: "Generated by create next app",
};


export default async function Dashboard() {
  const session = await auth()
  return (
    <>
    <Navbar />
    </>
  )
}
