import { Metadata } from "next"
import { auth } from "@/auth";
import { GetUser } from "@/actions/user/GetUser";
import { redirect } from "next/navigation";
import { GetAllUserPages } from "@/actions/page/GetAllUserPages";
import { Button } from "@/components/ui/button";
import { Plus } from "lucide-react";
import { PageCard } from "@/components/PageCard";

export const metadata: Metadata = {
    title: "Astralics | Overview",
    description: "Generated by create next app",
};
  
export default async function Page() {
    const session = await auth();
    if(!session) redirect('/login');
    const user = await GetUser();
    const pages = await GetAllUserPages();
    return (
        <>
        <div className="flex justify-between items-center w-full">
        <h1 className="font-bold text-2xl">Overview</h1>
        <Button> <Plus className="w-4 h-4 mr-2"/> Create new page</Button>
        </div>
        {pages.pages?.map((page) => {
            return (
                <>
                <PageCard title={page.name} website={page.website}/>
                </>
            )
        })}
        {JSON.stringify(pages)}
        </>
    )
}