import { Metadata } from "next";
import { TableComponent } from "@/components/TableComponent";

export const metadata: Metadata = {
    title: "Astralics | Feedback",
    description: "Generated by create next app",
};
  
export default async function Page() {
    return (
        <>
        <TableComponent />
        </>
    )
}