import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Astralics | Issues",
    description: "Generated by create next app",
};
  
export default async function Page() {
    return (
        <>
        </>
    )
}